AT:
  # Enable/Disable AdminTools.
  is_enabled: true
  debug: false
  # Should the tutorial class be in God Mode? Default: true
  god_tuts: true
CommonUtilities:
  # Whether or not debug messages should be shown.
  debug: false
  # The SCP Roles able to use V to talk to humans.
  scp_speech:
  - Scp049
  # Whether or not MTF/CI can 'escape' while disarmed to switch teams.
  disarm_switch_teams: true
  # Whether or not disarmed people will be prevented from interacting with doors/elevators.
  restrictive_disarming: true
  # The text displayed at the timed interval specified below.
  timed_broadcast: <color=lime>This server is running </color><color=red>EXILED Common-Utilities</color><color=lime>, enjoy your stay!</color>
  # The time each timed broadcast will be displayed.
  timed_broadcast_duration: 5
  # The delay between each timed broadcast. To disable timed broadcasts, set this to 0
  timed_broadcast_delay: 0
  # The message displayed to the player when they first join the server. Setting this to empty will disable these broadcasts.
  join_message: <color=red>Welcome %player% to the ICP facility!</color>
  # The amount of time (in seconds) the join message is displayed.
  join_message_duration: 10
  # The amount of time (in seconds) after the round starts, before the facilities auto-nuke will start.
  autonuke_time: 1500
  # Wether or not the nuke should be unable to be disabled during the auto-nuke countdown.
  autonuke_lock: true
  # The message given to all players when the auto-nuke is triggered. A duration of 2 or more will be a text message on-screen. A duration of 1 makes it a cassie announcement. A duration of 0 disables it.
  autonuke_broadcast:
    # The broadcast content
    content: The Alpha Warhead has been auto activated!
    # The broadcast duration
    duration: 10
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # Whether or not to show player's health under their name when you look at them.
  player_health_info: true
  # Whether or not friendly fire should automatically turn on when a round ends (it will turn itself back off before the next round starts).
  friendly_fire_on_round_end: false
  # The multiplier applied to radio battery usage. Set to 0 to disable radio battery drain.
  radio_battery_drain_multiplier: 0.5
  # The color to use for lights while the warhead is active.
  warhead_color:
    r: 1
    g: 0.6
    b: 0.2
    a: 1
  # The maximum time, in seconds, that a player can be AFK before being kicked. Set to -1 to disable AFK system.
  afk_limit: 0
  # The roles that are ignored by the AFK system.
  afk_ignored_roles:
  - Scp079
  - Spectator
  - Tutorial
  # The list of starting items for roles. ItemName is the item to give them, and Chance is the percent chance of them spawning with it, and Group allows you to restrict the item to only players with certain RA groups (Leave this as 'none' to allow all players to get the item). You can specify the same item multiple times.
  starting_inventories:
    ClassD:
      slot1:
      - item_name: KeycardJanitor
        chance: 0
        group: none
      - item_name: Coin
        chance: 0
        group: none
      slot2:
      - item_name: Flashlight
        chance: 0
        group: none
      slot3: []
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
      ammo:
      - type: Ammo556x45
        amount: 0
        group: none
  # The list of custom 914 recipies. Original is the item being upgraded, New is the item to upgrade to, and Chance is the percent chance of the upgrade happening. You can specify multiple upgrade choices for the same item.
  # KeycardJanitor                0      Keycard
  # KeycardScientist              1      Keycard
  # KeycardResearchCoordinator    2      Keycard
  # KeycardZoneManager            3      Keycard
  # KeycardGuard                  4      Keycard
  # KeycardNTFOfficer             5      Keycard
  # KeycardContainmentEngineer    6      Keycard     
  # KeycardNTFLieutenant          7      Keycard
  # KeycardNTFCommander           8      Keycard
  # KeycardFacilityManager        9      Keycard
  # KeycardChaosInsurgency       10      Keycard
  # KeycardO5                    11      Keycard
  scp914_item_changes:
    Rough:
    - original: KeycardNTFLieutenant
      new: KeycardGuard
      chance: 100
    - original: KeycardNTFCommander
      new: KeycardNTFOfficer
      chance: 100
    - original: KeycardZoneManager
      new: None
      chance: 100
    Coarse:
    - original: KeycardZoneManager
      new: KeycardJanitor
      chance: 100
    - original: KeycardFacilityManager
      new: KeycardResearchCoordinator
      chance: 100
    - original: KeycardO5
      new: KeycardFacilityManager
      chance: 100
    - original: GunRevolver
      new: GunCOM18
      chance: 100
    - original: GunShotgun 
      new: GunRevolver 
      chance: 100
    - original: ParticleDisruptor 
      new: ParticleDisruptor 
      chance: 50
    - original: ParticleDisruptor 
      new: None 
      chance: 50
    OneToOne:
    - original: KeycardZoneManager
      new: KeycardScientist
      chance: 100
    - original: KeycardFacilityManager
      new: KeycardFacilityManager
      chance: 100
    - original: KeycardO5
      new: KeycardNTFCommander
      chance: 100
    - original: ParticleDisruptor 
      new: ParticleDisruptor 
      chance: 100
    Fine:
    - original: KeycardContainmentEngineer
      new: KeycardGuard
      chance: 50
    - original: KeycardContainmentEngineer
      new: KeycardResearchCoordinator
      chance: 50
    - original: KeycardGuard
      new: KeycardGuard
      chance: 50
    - original: KeycardGuard
      new: KeycardScientist
      chance: 25
    - original: KeycardGuard
      new: KeycardNTFOfficer
      chance: 25
    - original: KeycardNTFOfficer
      new: KeycardNTFOfficer
      chance: 50
    - original: KeycardNTFOfficer
      new: KeycardResearchCoordinator
      chance: 25
    - original: KeycardNTFOfficer
      new: KeycardNTFLieutenant
      chance: 25
    - original: KeycardNTFLieutenant
      new: KeycardNTFLieutenant
      chance: 34
    - original: KeycardNTFLieutenant
      new: KeycardContainmentEngineer
      chance: 33
    - original: KeycardNTFLieutenant
      new: KeycardNTFCommander
      chance: 33
    - original: KeycardNTFCommander
      new: KeycardNTFCommander
      chance: 34
    - original: KeycardNTFCommander
      new: KeycardGuard
      chance: 33
    - original: KeycardNTFCommander
      new: KeycardFacilityManager
      chance: 33
    - original: KeycardChaosInsurgency
      new: KeycardChaosInsurgency
      chance: 34
    - original: KeycardChaosInsurgency
      new: KeycardGuard
      chance: 33
    - original: KeycardChaosInsurgency
      new: KeycardFacilityManager
      chance: 33
    - original: KeycardZoneManager
      new: KeycardGuard
      chance: 100
    - original: KeycardFacilityManager
      new: KeycardO5
      chance: 30
    - original: KeycardFacilityManager
      new: None
      chance: 70
    VeryFine:
    - original: KeycardJanitor
      new: KeycardResearchCoordinator
      chance: 50
    - original: KeycardJanitor
      new: KeycardJanitor
      chance: 50
    - original: KeycardScientist
      new: KeycardContainmentEngineer
      chance: 50
    - original: KeycardScientist
      new: KeycardScientist
      chance: 50
    - original: KeycardContainmentEngineer
      new: KeycardNTFLieutenant
      chance: 25
    - original: KeycardContainmentEngineer
      new: None
      chance: 75
    - original: KeycardGuard
      new: KeycardNTFOfficer
      chance: 75
    - original: KeycardGuard
      new: None
      chance: 25
    - original: KeycardNTFOfficer
      new: KeycardNTFLieutenant
      chance: 67
    - original: KeycardNTFOfficer
      new: KeycardNTFLieutenant
      chance: 33
    - original: KeycardNTFLieutenant
      new: KeycardNTFCommander
      chance: 60
    - original: KeycardNTFLieutenant
      new: None
      chance: 40
    - original: KeycardNTFCommander
      new: KeycardO5
      chance: 50
    - original: KeycardNTFCommander
      new: None
      chance: 50
    - original: KeycardChaosInsurgency
      new: SCP2176
      chance: 50
    - original: KeycardChaosInsurgency
      new: SCP1853
      chance: 50
    - original: KeycardZoneManager
      new: KeycardZoneManager
      chance: 99
    - original: KeycardZoneManager
      new: KeycardFacilityManager
      chance: 1
    - original: GunCOM15
      new: GunFSP9
      chance: 50
    - original: GunCOM15
      new: GunRevolver
      chance: 35
    - original: GunCOM15
      new: GunCom45
      chance: 15
    - original: GunRevolver
      new: GunShotgun
      chance: 60
    - original: GunRevolver
      new: None
      chance: 40
    - original: GunShotgun
      new: GunAK
      chance: 40
    - original: GunShotgun
      new: GunLogicer
      chance: 45
    - original: GunShotgun
      new: ParticleDisruptor
      chance: 25
    - original: GrenadeFlash
      new: None
      chance: 25
    - original: GrenadeFlash
      new: GrenadeFlash
      chance: 25
    - original: GrenadeFlash
      new: GrenadeHE
      chance: 25
    - original: GrenadeFlash
      new: SCP2176
      chance: 25
  
  # The list of custom 914 recipies for roles. Original is the role to be changed, New is the new role to assign, Chance is the % chance of the upgrade occuring.
  scp914_class_changes:
    Rough:
    - original: ClassD
      new: Spectator
      chance: 0
      keep_inventory: true
  # The list of 914 teleport settings. Note that if you set "zone" to anything other than Unspecified, it will always select a random room from that zone, instead of the room type defined.
  scp914_teleport_chances:
    Rough:
    - zone: Unspecified
      room: LczClassDSpawn
      offset:
        x: 0
        y: 0
        z: 0
      chance: 0
      damage: 0
  # A dictionary of random effects to apply to players when going through 914 on certain settings.
  scp914_effect_chances:
    Rough:
    - effect: AmnesiaVision
      chance: 0
      duration: 0
  # Determines if 914 effects are exclusive, meaning only one can be applied each time a player is processed by 914.
  scp914_effects_exclusivity: false
  # Whether or not SCPs are immune to effects gained from 914.
  scps_immune_to914_effects: false
  # The frequency (in seconds) between ragdoll cleanups. Set to 0 to disable.
  ragdoll_cleanup_delay: 0
  # If ragdoll cleanup should only happen in the Pocket Dimension or not.
  ragdoll_cleanup_only_pocket: false
  # The frequency (in seconds) between item cleanups. Set to 0 to disable.
  item_cleanup_delay: 0
  # If item cleanup should only happen in the Pocket Dimension or not.
  item_cleanup_only_pocket: false
  # A list of all roles and their damage modifiers. The number here is a multiplier, not a raw damage amount. Thus, setting it to 1 = normal damage, 1.5 = 50% more damage, and 0.5 = 50% less damage.
  role_damage_multipliers:
    Scp173: 1
  # A list of all Weapons and their damage modifiers. The number here is a multiplier, not a raw damage amount. Thus, setting it to 1 = normal damage, 1.5 = 50% more damage, and 0.5 = 50% less damage.
  damage_multipliers:
    E11Sr: 1
  # A list of roles and how much health they should be given when they kill someone.
  health_on_kill:
    Scp173: 0
    Scp939: 10
  # A list of roles and what their default starting health should be.
  health_values:
    Scp173: 3200
    NtfCaptain: 150
  # If the plugin is enabled or not.
  is_enabled: true
exiled_credits:
  is_enabled: true
  debug: false
  # Info side - Badge, CustomPlayerInfo, FirstAvailable
  mode: FirstAvailable
  # Overrides badge if exists
  badge_override: false
  # Overrides Custom Player Info if exists
  custom_player_info_override: false
  # Whether or not the plugin should ignore a player's DNT flag. By default (false), players with DNT flag will not be checked for credit tags.
  ignore_dnt_flag: false
exiled_custom_items:
  # Indicates whether this plugin is enabled or not.
  is_enabled: true
  debug: false
  # The hint that is shown when someone pickups a custom item.
  picked_up_hint:
    # The broadcast content
    content: >-
      You have picked up a {0}

      {1}
    # The broadcast duration
    duration: 10
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown when someone selects a custom item.
  selected_hint:
    # The broadcast content
    content: >-
      You have selected a {0}

      {1}
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
exiled_custom_roles:
  # Whether or not the plugin is enabled.
  is_enabled: true
  # Whether or not debug messages should be shown.
  debug: false
  # The hint that is shown when someone gets a custom role.
  got_role_hint:
    # The broadcast content
    content: >-
      You have spawned as a {0}

      {1}
    # The broadcast duration
    duration: 6
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # The hint that is shown when someone used a custom ability.
  used_ability_hint:
    # The broadcast content
    content: >-
      Ability {0} has been activated.

      {1}
    # The broadcast duration
    duration: 5
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
exiled_events:
  is_enabled: true
  debug: false
  # Indicates whether SCP-173 can be blocked or not by the tutorial
  can_tutorial_block_scp173: true
  # Indicates whether SCP-096 can be triggered or not by the tutorial
  can_tutorial_trigger_scp096: true
  # Indicates whether flashbangs flash original thrower.
  can_flashbangs_affect_thrower: true
  # Indicates whether the name tracking is enabled or not
  is_name_tracking_enabled: true
  # Indicates whether the inventory should be dropped before being set as spectator, through commands or plugins
  should_drop_inventory: true
  # Indicates whether the blood can be spawned or not
  can_spawn_blood: true
  # Indicates whether thrown keycards can affect doors that don't require any permissions
  can_keycard_throw_affect_doors: true
  # Indicates whether configs have to be reloaded every round restart
  should_reload_configs_at_round_restart: false
  # Indicates whether translations has to be reloaded every round restart
  should_reload_translations_at_round_restart: false
  # Indicates whether bans should be logged or not
  should_log_bans: true
  # Whether or not to log RA commands.
  log_ra_commands: true
exiled_permissions:
  # Indicates whether the debug should be shown or not
  should_debug_be_shown: false
  # The permissions folder path
  folder: /home/scpserver/.config/EXILED/Configs
  # The permissions full path
  full_path: /home/scpserver/.config/EXILED/Configs/permissions.yml
  is_enabled: true
  debug: false
exiled_updater:
  is_enabled: true
  debug: false
  # Indicates whether the debug should be shown or not
  should_debug_be_shown: false
  # Indicates whether testing releases have to be downloaded or not
  should_download_testing_releases: false
  # Indicates which assemblies should be excluded from the update
  exclude_assemblies: []
scripted_events:
  # Whether or not to enable the Scripted Events plugin.
  is_enabled: true
  debug: false
  # Enable logs for starting/stopping scripts.
  enable_logs: true
  # If a script encounters an error, broadcast a notice to the person who ran the command, informing of the error. The broadcast ONLY shows to the command executor.
  broadcast_issues: true
  # If set to true, players with overwatch enabled will not be affected by any commands related to players.
  ignore_overwatch: true
  # List of scripts to run as soon as the round starts.
  auto_run_scripts:
  - LIGHTSOFF
  # List of scripts to automatically re-run as soon as they finish.
  loop_scripts: []
  # The string to use for countdowns.
  countdown_string: <size=26><color=#5EB3FF><b>{TEXT}</b></color></size>\n{TIME}
  # Define a custom set of actions and the action they run when used.
  aliases:
  - command: LOCKDOORBRIEF
    execute: DOOR LOCK * 10
  # Define a custom set of permissions used to run a certain script. The provided permission will be added AFTER script.execute (eg. script.execute.examplepermission for the provided example).
  required_permissions:
    ExampleScriptNameHere: examplepermission
  # [ADVANCED] Define scripts to execute when certain events occur.
  on: {}
