user:
  default: true
  inheritance: [ ]
  permissions:
    - testplugin.user

owner:
  inheritance: [ ]
  permissions:
    - .*

admin:
  inheritance:
    - moderator
  permissions:
    - .*

moderator:
  inheritance: [ ]
  permissions:
    - testplugin.moderator
